/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#85f5ec',
        'surface-container': '#f0eded',
        'on-secondary-container': '#006f69',
        'surface': '#fcf9f8',
        'on-tertiary-fixed-variant': '#00504c',
        'on-primary-fixed': '#00201d',
        'outline': '#6c7a77',
        'on-background': '#1b1c1c',
        'on-error-container': '#93000a',
        'on-surface': '#1b1c1c',
        'surface-tint': '#006a62',
        'tertiary-container': '#2ba7a0',
        'background': '#fcf9f8',
        'tertiary': '#006a65',
        'secondary': '#006a64',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#dcd9d9',
        'on-primary-fixed-variant': '#00504a',
        'primary-fixed': '#78f7e9',
        'on-tertiary-container': '#003633',
        'surface-container-highest': '#e5e2e1',
        'on-secondary-fixed': '#00201e',
        'on-primary-container': '#003631',
        'error-container': '#ffdad6',
        'surface-container-low': '#f6f3f2',
        'surface-bright': '#fcf9f8',
        'primary-fixed-dim': '#59dacd',
        'inverse-surface': '#303030',
        'on-secondary-fixed-variant': '#00504b',
        'outline-variant': '#bbc9c6',
        'error': '#ba1a1a',
        'primary': '#006a62',
        'inverse-primary': '#59dacd',
        'on-tertiary-fixed': '#00201e',
        'on-error': '#ffffff',
        'secondary-container': '#77f3e9',
        'secondary-fixed': '#7af6ec',
        'surface-variant': '#e5e2e1',
        'on-tertiary': '#ffffff',
        'on-surface-variant': '#3c4947',
        'tertiary-fixed-dim': '#67d8d0',
        'surface-container-high': '#eae7e7',
        'secondary-fixed-dim': '#5bdad0',
        'primary-container': '#00a99d',
        'inverse-on-surface': '#f3f0ef',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-desktop': '40px',
        xl: '32px',
        md: '16px',
        'margin-mobile': '16px',
        gutter: '24px',
        xs: '4px',
        sm: '8px',
        '2xl': '48px',
        unit: '4px',
        lg: '24px',
        '3xl': '64px',
      },
      fontFamily: {
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Hanken Grotesk', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'display-lg': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
